### PR TITLE
Post attachment view

### LINKED ISSUE #151: Post attachment view is not working
### What steps will reproduce the problem?
Click on the attached image of the post

### What's expected?
Open file view window

### What do you get instead?
Nothing is happening

### PR DESCRIPTION
**Pull request by ll-bat**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #151

### CODE REVIEW

File: modules/v1/workspaces/models/Folder.php [hunk 1]
```diff
@@ -228,4 +230,39 @@ public function uploadFile(UploadedFile $file, $workspaceId)
...
+        $dest =  Yii::getAlias("@storage/$newFilePath");
+
+        $this->name = substr($fileName, 0, strrpos($fileName, '.') + 1) . 'webp';
+        $this->mime = 'image/webp';
+        $this->file_path = $newFilePath;
+
+        $im = new Imagick();
+        $im->pingImage($src);
+        $im->readImage($src);
+        $im->resizeImage($width,$height, Imagick::FILTER_CATROM , 1,TRUE );
```
Comment (thecodeholic) [inline modules/v1/workspaces/models/Folder.php]: Code is not formatted

File: composer.json [hunk 2]
```diff
@@ -22,7 +22,8 @@
         "vlucas/phpdotenv": "^5.1@dev",
         "intermundia/yii2-mailer": "*",
         "creocoder/yii2-nested-sets": "^0.9.0",
-        "ext-json": "*"
+        "ext-json": "*",
+      "ext-imagick": "*"
```
Comment (thecodeholic) [inline composer.json]: Let's try to use this package, which is official package of yiisoft
https://github.com/yiisoft/yii2-imagine

File: modules/v1/workspaces/resources/TimelinePostResource.php [hunk 3]
```diff
@@ -130,8 +131,12 @@ public function getMyLikes()
      */
     public function getFileUrl()
     {
-        $folder = FolderResource::findOne(['timeline_post_id' => $this->id]);
-        return $folder ? Yii::getAlias('@storageUrl' . $folder->file_path) : '';
+        $folders = FolderResource::findAll(['timeline_post_id' => $this->id]);
+        $files = ['original' => null, 'converted' => null];
+        foreach ($folders as $folder) {
+            $files[$folder->mime === 'image/webp' ? 'converted' : 'original'] = Yii::getAlias('@storageUrl' . $folder->file_path);
```
Comment (thecodeholic) [inline modules/v1/workspaces/resources/TimelinePostResource.php]: This is not quite correct, because user might upload webp as original image also.
```php
$folder->mime === 'image/webp' ? 'converted' : 'original'
```

File: modules/v1/workspaces/resources/TimelinePostResource.php [hunk 4]
```diff
@@ -182,16 +202,30 @@ public function afterSave($insert, $changedAttributes)
...
 
-        if (!$folder) {
+        if (!$folders) {
             return parent::beforeDelete();
         }
 
-        if (!ModelHelper::deleteFile($folder->file_path)) {
-            throw new ValidationException(Yii::t('app', 'Unable to delete timeline file'));
+        foreach ($folders as $folder) {
+            if (file_exists(Yii::getAlias("@storage/" . $folder->file_path)) && !ModelHelper::deleteFile($folder->file_path)) {
```
Comment (thecodeholic) [inline modules/v1/workspaces/resources/TimelinePostResource.php:252]: Better if Folder has a method `deleteFile` and we don't use ModelHelper and and also checking if file_exists goes inside that method

File: modules/v1/workspaces/resources/TimelinePostResource.php [hunk 5]
```diff
@@ -182,16 +202,30 @@ public function afterSave($insert, $changedAttributes)
...
     }
+
+    /**
+     * @param String $path
+     * @return bool
+     */
+    public function isImage(string $path)
+    {
+        $extension = strtolower(substr($path, strrpos($path, '.') + 1));
+        return in_array($extension, ['png', 'jpeg', 'svg', 'gif', 'jpg']);
```
Comment (thecodeholic) [inline modules/v1/workspaces/resources/TimelinePostResource.php]: webp is not in this list

File: modules/v1/workspaces/resources/TimelinePostResource.php [hunk 6]
```diff
@@ -182,16 +202,30 @@ public function afterSave($insert, $changedAttributes)
...
+        FolderResource::deleteAll(['timeline_post_id' => $this->id]);
+
         return parent::beforeDelete();
     }
+
+    /**
+     * @param String $path
+     * @return bool
+     */
+    public function isImage(string $path)
```
Comment (thecodeholic) [inline modules/v1/workspaces/resources/TimelinePostResource.php]: There already exists a method in ModelHelper for this purpose.

File: vue/src/modules/Workspace/view/timeline/TimelineItem.vue [hunk 7]
```diff
@@ -46,11 +46,11 @@
       </div>
     </b-card-body>
     <div v-if="timeline.file_url" class="timeline-preview">
-      <div v-if="isImage(timeline.file_url)" class="image-preview">
-        <b-img :src="timeline.file_url" class="img-fluid" style="cursor: pointer"/>
+      <div v-if="timeline.file_url.original && isImage(timeline.file_url.original)" class="image-preview">
+        <b-img :src="timeline.file_url.converted" @error="loadOriginalImage" @click="previewModal" class="img-fluid" style="cursor: pointer"/>
```
Comment (thecodeholic) [inline vue/src/modules/Workspace/view/timeline/TimelineItem.vue]: If converted does not exist for some reason we should fallback to original image.

File: modules/v1/workspaces/models/Folder.php [hunk 8]
```diff
@@ -252,4 +254,39 @@ public function uploadFile(UploadedFile $file, $workspaceId)
...
+        $src = Yii::getAlias("@storage/$filePath");
+        list($width1, $height1) = getimagesize($src);
+
+        $width = $imageWidth;
+        $height = $height1 * ($imageWidth / $width1);
+        $newFilePath = substr($filePath, 0, strrpos($filePath, '.') + 1) . 'webp';
+        $dest =  Yii::getAlias("@storage/$newFilePath");
+
+        $this->name = substr($fileName, 0, strrpos($fileName, '.') + 1) . 'webp';
+        $this->mime = 'image/webp';
```
Comment (thecodeholic) [inline modules/v1/workspaces/models/Folder.php:295]: We need to find a different way to convert into webp. This method reduces the image quality a lot. If you upload image with source code it is hard to read after converting.
This is the best method to convert into webp
https://developers.google.com/speed/webp/docs/cwebp

File: vue/src/modules/Workspace/view/timeline/TimelineItem.vue [hunk 9]
```diff
@@ -145,6 +145,15 @@ export default {
         await this.like(params);
       }
     },
+    previewModal() {
+      this.showPreviewModal({
+        activeFile: 0,
+        files: [{file_path: this.timeline.file_url.original, mime: 'image/png', name: this.$t('Uploaded image')}]
```
Comment (thecodeholic) [inline vue/src/modules/Workspace/view/timeline/TimelineItem.vue]: We should not have `image/png` hardcoded.

File: modules/v1/workspaces/models/Folder.php [hunk 10]
```diff
@@ -252,4 +254,39 @@ public function uploadFile(UploadedFile $file, $workspaceId)
...
+     */
+    public function convertUploadedFile($filePath, $fileName)
+    {
+        $imageWidth = 680;
+        $src = Yii::getAlias("@storage/$filePath");
+        list($width1, $height1) = getimagesize($src);
+
+        $width = $imageWidth;
+        $height = $height1 * ($imageWidth / $width1);
+        $newFilePath = substr($filePath, 0, strrpos($filePath, '.') + 1) . 'webp';
```
Comment (thecodeholic) [inline modules/v1/workspaces/models/Folder.php]: Getting filename like this is not correct. What if the filename is called `something.test.jpg`?
