### PR TITLE
Fix file manager bugs

### LINKED ISSUE #111: The size of Create Folder
- Reduce the size of the Create Folder
- Change "Title" to "Name"

### LINKED ISSUE #112: Cursor Focus
The focus should be on the first input field where the input fields are across the Workspace, such as Create articles, Creat folder so on.

### LINKED ISSUE #113: Updated by
Across the workspace functionality, where the Update by columns exists, is missing the values. ( e.g. over photo upload)

### LINKED ISSUE #114: Delete Message
When deleting a file, the message text should be changed to 1 file(s) was deleted. We can discuss over the message text when start working on it.

### LINKED ISSUE #116: Updated at
Check across the workspace (e.g. folder) when I update an item, the updated at date changes to "1970" and the update modal doesn't display the folder name.

### PR DESCRIPTION
**Pull request by skavt**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Tests pass?   | no
| Fixed issues  | #113 #116 #112 #114 #111

### CODE REVIEW

File: vue/src/modules/Workspace/view/files/WorkspaceFiles.vue [hunk 1]
```diff
@@ -164,7 +164,7 @@ export default {
       if (result) {
         const res = await this.deleteFolder(fileIds);
         if (res.success) {
-          this.$toast(this.$t(`{count} file(s) and folder(s) were successfully deleted`, {count: fileIds.length}));
+          this.$toast(this.$t(`file(s) were successfully deleted`));
```
Comment (saiat3) [inline vue/src/modules/Workspace/view/files/WorkspaceFiles.vue]: @skavt Please start messages with upper case `File(s) were successfully deleted`
